[project]
name = "blender-on-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
    "streamlit-extras>=0.6.0",
    "watchdog>=6.0.0",
]
